USE TestSqlServer;

SELECT
  MP.NUMPEDIDO,
  CP.CLIE,
  CP.REP,
  CP.CLIENTE,
  CP.REPCLIE,
  CP.Vendedor_asignado AS VENDEDOR,
  MP.FAB,
  MP.PRODUCTO,
  MP.CANT,
  MP.IMPORTE
FROM
  CLIENTEPEDIDO CP
JOIN
  MOVIMIENTOPEDIDO MP ON CP.NUMPEDIDO = MP.NUMPEDIDO;