CREATE TABLE PROPIETARIOS(
	DNI VARCHAR(9) PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(50),
	DIRECCION VARCHAR(100)
);


CREATE TABLE LOCALES(
	CODIGO VARCHAR(5) PRIMARY KEY NOT NULL,
	DNI VARCHAR(9),
	UBICACION VARCHAR(100),
	SUPERFICIE DECIMAL(10,2),
	FOREIGN KEY (DNI) REFERENCES PROPIETARIOS(DNI)
);